name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.ruby }} ${{ matrix.rails }} ${{ matrix.gem }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: 
          - 3.0
        include:
          - rails: 6.0.5
            gem: rails_6.0
          - rails: 6.1.6
            gem: rails_6.1

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY  

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project. 
