name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.fruit }} ${{ matrix.animal }}  ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: 
          - 3
        include:
          - color: green1
            animal: cat1
          - color: green2
            animal: cat2

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY  

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project. 
